Config 						= {}

--GENERAL
Config.Lang             	= 'fa'    	--Set lang (fa-en)
Config.permission       	= 3	   	  	--Permission need to use FiveM-BanSql commands
Config.MultiServerSync  	= false   	--This will check if a ban is add in the sql all 30 second, use it only if you have more then 1 server (true-false)

--WEBHOOK
--ANTICHEAT
Config.ExplosionLog 		= ""
Config.AntiEntityLog 		= ""
--BAN
Config.EnableDiscordLink	= false 	--Turn this true if you want link the log to a discord (true-false)
Config.webhookban        	= ""
Config.webhookunban      	= ""

--ANTICHEAT CONFIG
--BLACKLIST WEAPONS
Config.BlacklistedWeapons = {
"weapon_fireextinguisher",
"WEAPON_SPECIALCARBINE",
"weapon_flare",
"weapon_smokegrenade",
"weapon_ball",
"weapon_pipebomb",
"weapon_snowball",
"weapon_proxmine",
"weapon_stickybomb",
"weapon_molotov",
"weapon_bzgas",
"weapon_grenade",
"weapon_rayminigun",
"weapon_compactlauncher",
"weapon_hominglauncher",
"weapon_railgun",
"weapon_firework",
"weapon_minigun",
"weapon_grenadelauncher_smoke",
"weapon_grenadelauncher",
"weapon_rpg",
--"weapon_sniperrifle",
"weapon_heavysniper",
"weapon_heavysniper_mk2",
"weapon_marksmanrifle",
"weapon_marksmanrifle_mk2",
"weapon_mg",
"weapon_combatmg",
"weapon_combatmg_mk2",
"weapon_bullpuprifle_mk2",
"weapon_assaultrifle_mk2",
"weapon_carbinerifle_mk2",
"weapon_specialcarbine_mk2",
"weapon_bullpuprifle",
"weapon_autoshotgun",
"weapon_dbshotgun",
"weapon_heavyshotgun",
"weapon_musket",
"weapon_bullpupshotgun",
"weapon_assaultshotgun",
"weapon_sawnoffshotgun",
"weapon_pumpshotgun_mk2",
"weapon_smg_mk2",
"weapon_machinepistol",
"weapon_minismg",
"weapon_raycarbine",
"weapon_navyrevolver",
"weapon_ceramicpistol",
"weapon_raypistol",
"weapon_revolver_mk2",
"weapon_revolver",
"weapon_marksmanpistol",
"weapon_flaregun",
"weapon_snspistol_mk2",
"weapon_pistol_mk2",
"weapon_stone_hatchet",
"weapon_poolcue",
"weapon_battleaxe",
"weapon_wrench",
"weapon_dagger",
"weapon_golfclub",
"weapon_crowbar",
}

--BLACKLIST VEHICLES
Config.BlacklistedModels = {
    [GetHashKey("luxor2")] = {name = "Luxur2", ban = true, kick = false},
    [GetHashKey("dump")] = {name = "Dump", ban = true, kick = false},
    [GetHashKey("avenger")] = {name = "Avenger", ban = true, kick = false},
    [GetHashKey("avenger2")] = {name = "Avenger2", ban = true, kick = false},
    [GetHashKey("luxor")] = {name = "Luxor", ban = false},
    [GetHashKey("khanjali")] = {name = "Khanjali", ban = true, kick = false},
    [GetHashKey("rhino")] = {name = "Rhino", ban = true, kick = false},
    [GetHashKey("insurgent")] = {name = "Insurgent", ban = true, kick = false},
    [GetHashKey("oppressor")] = {name = "Oprresor", ban = true, kick = false},
    [GetHashKey("oppressor2")] = {name = "Oprresor2", ban = true, kick = false},
    [GetHashKey("maverick")] = {name = "Maverick", ban = true, kick = false},
    [GetHashKey("blimp2")] = {name = "blimp2", ban = true, kick = false},
    [GetHashKey("blimp")] = {name = "blimp", ban = false},
    [GetHashKey("blimp3")] = {name = "blimp3", ban = true, kick = false},
    [GetHashKey("freight")] = {name = "Freight", ban = true, kick = false},
    [GetHashKey("freightcar")] = {name = "FreightCar", ban = true, kick = false},
    [GetHashKey("limo2")] = {name = "Limo2", ban = true, kick = false},
    [GetHashKey("freightcont1")] = {name = "FreightCont1", ban = true, kick = false},
    [GetHashKey("freightcont2")] = {name = "FreightCont2", ban = true, kick = false},
    [GetHashKey("freightgrain")] = {name = "FreightGrain", ban = true, kick = false},
    [GetHashKey("cerberus3")] = {name = "Cerberus3", ban = true, kick = false},
    [GetHashKey("cerberus2")] = {name = "Cerberus2", ban = true, kick = false},
    [GetHashKey("cerberus")] = {name = "Cerberus", ban = true, kick = false},
    [GetHashKey("buzzard")] = {name = "Buzzard", ban = false},
    [GetHashKey("phantom2")] = {name = "Phantom2", ban = true, kick = false},
    [GetHashKey("issi6")] = {name = "Issi6", ban = true, kick = false},
    [GetHashKey("issi4")] = {name = "Issi4", ban = true, kick = false},
    [GetHashKey("issi5")] = {name = "Issi5", ban = true, kick = false},
    [GetHashKey("savage")] = {name = "Savage", ban = true, kick = false},
    [GetHashKey("hunter")] = {name = "Hunter", ban = true, kick = false},
    [GetHashKey("akula")] = {name = "Akula", ban = true, kick = false},
    [GetHashKey("annihilator")] = {name = "Annihilator", ban = true, kick = false},
    [GetHashKey("cutter")] = {name = "Cutter", ban = true, kick = false},
    [GetHashKey("bulldozer")] = {name = "Bulldozer", ban = true, kick = false},
    [GetHashKey("barracks")] = {name = "Barracks", ban = true, kick = false},
    [GetHashKey("barracks2")] = {name = "Barracks2", ban = true, kick = false},
    [GetHashKey("barracks3")] = {name = "Barracks3", ban = true, kick = false},
    [GetHashKey("barrage")] = {name = "Barrage", ban = true, kick = false},
    [GetHashKey("chernobog")] = {name = "Chernobog", ban = true, kick = false},
    [GetHashKey("crusader")] = {name = "Crusader", ban = true, kick = false},
    [GetHashKey("halftrack")] = {name = "HalfTrack", ban = true, kick = false},
    [GetHashKey("minitank")] = {name = "MiniTank", ban = true, kick = false},
    [GetHashKey("scarab")] = {name = "Scarab", ban = true, kick = false},
    [GetHashKey("scarab2")] = {name = "Scarab2", ban = true, kick = false},
    [GetHashKey("scarab3")] = {name = "Scarab3", ban = true, kick = false},
    [GetHashKey("thruster")] = {name = "Thruster", ban = true, kick = false},
    [GetHashKey("trailersmall2")] = {name = "Trailersmall2", ban = true, kick = false},
    [GetHashKey("brutus3")] = {name = "Brutus3", ban = true, kick = false},
    [GetHashKey("freecrawler")] = {name = "Freecrawler", ban = true, kick = false},
    [GetHashKey("monster")] = {name = "Monster", ban = true, kick = false},
    [GetHashKey("technical")] = {name = "Technical", ban = true, kick = false},
    [GetHashKey("technical3")] = {name = "Technical3", ban = true, kick = false},
    [GetHashKey("technical2")] = {name = "Technical2", ban = true, kick = false},
    [GetHashKey("nightshark")] = {name = "Nightshark", ban = true, kick = false},
    [GetHashKey("zhaba")] = {name = "Zhaba", ban = true, kick = false},
    [GetHashKey("formula")] = {name = "Formula", ban = true, kick = false},
    [GetHashKey("formula2")] = {name = "Formula2", ban = true, kick = false},
    [GetHashKey("scramjet")] = {name = "Scramjet", ban = true, kick = false},
    [GetHashKey("zr3802")] = {name = "Zr3802", ban = true, kick = false},
    [GetHashKey("raptor")] = {name = "Raptor", ban = true, kick = false},
    [GetHashKey("volatol")] = {name = "Volatol", ban = true, kick = false},
    [GetHashKey("voltic2")] = {name = "Voltic2", ban = true, kick = false},
    [GetHashKey("tula")] = {name = "Tula", ban = true, kick = false},
    [GetHashKey("strikeforce")] = {name = "Strikeforce", ban = true, kick = false},
    [GetHashKey("lazer")] = {name = "Lazer", ban = true, kick = false},
    [GetHashKey("valkyrie2")] = {name = "Valkyrie2", ban = true, kick = false},
    [GetHashKey("jet")] = {name = "Jet", ban = false},
    [GetHashKey("hydra")] = {name = "Hydra", ban = true, kick = false},
    [GetHashKey("cargoplane")] = {name = "Cargoplane", ban = true, kick = false},
    [GetHashKey("bombushka")] = {name = "Bombushka", ban = true, kick = false},
    [GetHashKey("bruiser3")] = {name = "Bruiser3", ban = true, kick = false},
    [GetHashKey("bruiser2")] = {name = "Bruiser2", ban = true, kick = false},
	[GetHashKey("bruiser")] = {name = "Bruiser", ban = true, kick = false},
	[GetHashKey("caracara")] = {name = "Caracara", ban = true, kick = false},
    [GetHashKey("dune5")] = {name = "Dune5", ban = true, kick = false},
    [GetHashKey("dune4")] = {name = "Dune4", ban = true, kick = false},
    [GetHashKey("dune3")] = {name = "Dune3", ban = true, kick = false},
    [GetHashKey("dune2")] = {name = "Dune2", ban = true, kick = false},
    [GetHashKey("dune")] = {name = "Dune", ban = true}
}

Config.BlacklistedPeds = {
    [GetHashKey("a_m_y_mexthug_01")] = {name = "MexThug", ban = true, kick = false},
	[GetHashKey("A_C_MtLion")] = {name = "Lion", ban = true, kick = false},
    [GetHashKey("a_c_husky")] = {name = "Huskey", ban = true, kick = false}, 
    [GetHashKey("a_c_boar")] = {name = "Boar", ban = true, kick = false}, 
    [GetHashKey("a_c_sharkhammer")] = {name = "Sharkhammer", ban = true, kick = false}, 
    [GetHashKey("a_c_chimp")] = {name = "Chimp", ban = true, kick = false}, 
    [GetHashKey("a_c_chop")] = {name = "Chop", ban = true, kick = false}, 
    [GetHashKey("a_c_hen")] = {name = "Hen", ban = true, kick = false}, 
    [GetHashKey("a_c_humpback")] = {name = "Humpback", ban = true, kick = false}, 
    [GetHashKey("a_c_killerwhale")] = {name = "Killerwhale", ban = true, kick = false},
    [GetHashKey("a_c_rhesus")] = {name = "Rhesus", ban = true, kick = false}, 
    [GetHashKey("a_c_rottweiler")] = {name = "Rottweiler", ban = true, kick = false}, 
    [GetHashKey("a_c_sharktiger")] = {name = "SharkTiger", ban = true, kick = false}, 
    [GetHashKey("a_c_shepherd")] = {name = "Shepherd", ban = true, kick = false}, 
    [GetHashKey("u_m_y_zombie_01")] = {name = "Zombie", ban = true, kick = false},
    [GetHashKey("a_m_m_acult_01")] = {name = "Acult01", ban = true, kick = false},
    [GetHashKey("u_m_y_juggernaut_01")] = {name = "Juggernaut", ban = true, kick = false},
	[GetHashKey("s_m_y_swat_01")] = {name = "Swat", ban = true, kick = false},
	[GetHashKey("ig_wade")] = {name = "IG Wade(Tiago RPG)", ban = true, kick = false},
	[GetHashKey("a_m_m_afriamer_01")] = {name = "afriamer(Tiago AK Attack)", ban = true, kick = false},
	[GetHashKey("csb_stripper_02")] = {name = "stripper(Tiago RPG Attack)", ban = true, kick = false},
}

local WhitelistedEntities = {
    [GetHashKey("prop_mp_cone_01")] = 'prop_mp_cone_01',
	[GetHashKey("prop_mp_barrier_02b")] = 'prop_mp_barrier_02b',
	[GetHashKey("prop_barrier_work05")] = 'prop_barrier_work05',
	[GetHashKey("prop_mp_arrow_barrier_01")] = 'prop_mp_arrow_barrier_01',
	[GetHashKey("p_ld_stinger_s")] = 'p_ld_stinger_s',
	[GetHashKey("hei_prop_cash_crate_half_full")] = 'hei_prop_cash_crate_half_full',
	[GetHashKey("prop_roadcone02a")] = 'prop_roadcone02a',
	[GetHashKey("prop_toolchest_01")] = 'prop_toolchest_01',
	[GetHashKey("prop_ld_jerrycan_01")] = 'prop_ld_jerrycan_01',
	[GetHashKey("w_me_bat")] = 'w_me_bat',
	[GetHashKey("prop_golf_iron_01")] = 'prop_golf_iron_01',
	[GetHashKey("w_lr_firework")] = 'w_lr_firework',
	[GetHashKey("w_sr_sniperrifle")] = 'w_sr_sniperrifle',
	[GetHashKey("w_ar_carbinerifle")] = 'w_ar_carbinerifle',
	[GetHashKey("w_ar_assaultrifle")] = 'w_ar_assaultrifle',
	[GetHashKey("w_ar_specialcarbine")] = 'w_ar_specialcarbine',
	[GetHashKey("w_ar_bullpuprifle")] = 'w_ar_bullpuprifle',
	[GetHashKey("w_ar_advancedrifle")] = 'w_ar_advancedrifle',
	[GetHashKey("w_sg_assaultshotgun")] = 'w_sg_assaultshotgun',
	[GetHashKey("w_sg_bullpupshotgun")] = 'w_sg_bullpupshotgun',
	[GetHashKey("w_sg_pumpshotgun")] = 'w_sg_pumpshotgun',
	[GetHashKey("w_ar_musket")] = 'w_ar_musket',
	[GetHashKey("w_sb_microsmg")] = 'w_sb_microsmg',
	[GetHashKey("w_sb_assaultsmg")] = 'w_sb_assaultsmg',
	[GetHashKey("w_sb_smg")] = 'w_sb_smg',
	[GetHashKey("w_sb_gusenberg")] = 'w_sb_gusenberg',
	[GetHashKey("w_sb_combatpdw")] = 'w_sb_combatpdw',
	[GetHashKey("v_med_bed2")] = 'v_med_bed2',
	[GetHashKey("prop_amb_phone")] = 'prop_amb_phone',
	[GetHashKey("prop_cs_cardbox_01")] = 'prop_cs_cardbox_01',
	[GetHashKey("prop_cs_burger_01")] = 'prop_cs_burger_01',
	[GetHashKey("ba_prop_battle_glowstick_01")] = 'ba_prop_battle_glowstick_01',
	[GetHashKey("ba_prop_battle_hobby_horse")] = 'ba_prop_battle_hobby_horse',
	[GetHashKey("p_amb_brolly_01")] = 'p_amb_brolly_01',
	[GetHashKey("prop_notepad_01")] = 'prop_notepad_01',
	[GetHashKey("hei_prop_heist_box")] = 'hei_prop_heist_box',
	[GetHashKey("prop_single_rose")] = 'prop_single_rose',
	[GetHashKey("prop_cs_ciggy_01")] = 'prop_cs_ciggy_01',
	[GetHashKey("hei_heist_sh_bong_01")] = 'hei_heist_sh_bong_01',
	[GetHashKey("prop_ld_suitcase_01")] = 'prop_ld_suitcase_01',
	[GetHashKey("prop_security_case_01")] = 'prop_security_case_01',
	[GetHashKey("prop_police_id_board")] = 'prop_police_id_board',
	[GetHashKey("p_amb_coffeecup_01")] = 'p_amb_coffeecup_01',
	[GetHashKey("prop_drink_whisky")] = 'prop_drink_whisky',
	[GetHashKey("prop_amb_beer_bottle")] = 'prop_amb_beer_bottle',
	[GetHashKey("prop_plastic_cup_02")] = 'prop_plastic_cup_02',
	[GetHashKey("prop_amb_donut")] = 'prop_amb_donut',
	[GetHashKey("prop_sandwich_01")] = 'prop_sandwich_01',
	[GetHashKey("prop_ecola_can")] = 'prop_ecola_can',
	[GetHashKey("prop_choc_ego")] = 'prop_choc_ego',
	[GetHashKey("prop_drink_redwine")] = 'prop_drink_redwine',
	[GetHashKey("prop_champ_flute")] = 'prop_champ_flute',
	[GetHashKey("prop_drink_champ")] = 'prop_drink_champ',
	[GetHashKey("prop_cigar_02")] = 'prop_cigar_02',
	[GetHashKey("prop_cigar_01")] = 'prop_cigar_01',
	[GetHashKey("prop_acc_guitar_01")] = 'prop_acc_guitar_01',
	[GetHashKey("prop_el_guitar_01")] = 'prop_el_guitar_01',
	[GetHashKey("prop_el_guitar_03")] = 'prop_el_guitar_03',
	[GetHashKey("prop_novel_01")] = 'prop_novel_01',
	[GetHashKey("prop_snow_flower_02")] = 'prop_snow_flower_02',
	[GetHashKey("v_ilev_mr_rasberryclean")] = 'v_ilev_mr_rasberryclean',
	[GetHashKey("p_michael_backpack_s")] = 'p_michael_backpack_s',
	[GetHashKey("p_amb_clipboard_01")] = 'p_amb_clipboard_01',
	[GetHashKey("prop_beggers_sign_03")] = 'prop_beggers_sign_03',
	[GetHashKey("prop_anim_cash_pile_01")] = 'prop_anim_cash_pile_01',
	[GetHashKey("prop_pap_camera_01")] = 'prop_pap_camera_01',
	[GetHashKey("ba_prop_battle_champ_open")] = 'ba_prop_battle_champ_open',
	[GetHashKey("p_cs_joint_02")] = 'p_cs_joint_02',
	[GetHashKey("prop_amb_ciggy_01")] = 'prop_amb_ciggy_01',
	[GetHashKey("prop_ld_case_01")] = 'prop_ld_case_01',
	[GetHashKey("prop_cs_tablet")] = 'prop_cs_tablet',
	[GetHashKey("prop_npc_phone_02")] = 'prop_npc_phone_02',
	[GetHashKey("prop_sponge_01")] = 'prop_sponge_01',
	[GetHashKey("prop_boombox_01")] = 'prop_boombox_01',
	[1760825203] = 'no name',
	[1070220657] = 'cuff',
	[GetHashKey("prop_byard_ladder01")] = 'prop_byard_ladder01',
	[GetHashKey("w_ex_flashbang")] = 'w_ex_flashbang',
	[GetHashKey("prop_cs_hand_radio")] = 'prop_cs_hand_radio',
	[GetHashKey("prop_ld_flow_bottle")] = 'prop_ld_flow_bottle',
	[GetHashKey("prop_food_bs_burger2")] = 'prop_food_bs_burger2',
	[GetHashKey("prop_ld_snack_01")] = 'prop_ld_snack_01',
	[GetHashKey("prop_tourist_map_01")] = 'prop_tourist_map_01',
	[GetHashKey("prop_pencil_01")] = 'prop_pencil_01',
	[GetHashKey("ng_proc_sodacan_01b")] = 'ng_proc_sodacan_01b',
	[GetHashKey("w_pi_sns_pistol")] = 'w_pi_sns_pistol',
	[GetHashKey("w_pi_combatpistol")] = 'w_pi_combatpistol',
	[GetHashKey("w_pi_pistol50")] = 'w_pi_pistol50',
	[GetHashKey("w_pi_pistol")] = 'w_pi_pistol',
	[GetHashKey("w_pi_heavypistol")] = 'w_pi_heavypistol',
	[GetHashKey("w_sb_pdw")] = 'w_sb_pdw',
	[GetHashKey("w_me_bat")] = 'w_me_bat',
	[GetHashKey("w_me_crowbar")] = 'w_me_crowbar',
	[GetHashKey("w_me_gclub")] = 'w_me_gclub',
	[GetHashKey("w_me_hammer")] = 'w_me_hammer',
	[GetHashKey("w_me_nightstick")] = 'w_me_nightstick',
	[GetHashKey("w_me_knife_01")] = 'w_me_knife_01',
	[GetHashKey("v_ret_ml_chips2")] = 'v_ret_ml_chips2',
	[GetHashKey("prop_pizza_box_02")] = 'prop_pizza_box_02',
	[GetHashKey("v_ret_247_bread1")] = 'v_ret_247_bread1',
	[GetHashKey("ng_proc_sodacan_01a")] = 'ng_proc_sodacan_01a',
	[GetHashKey("p_cs_lighter_01")] = 'p_cs_lighter_01',
	[GetHashKey("prop_player_phone_01")] = 'prop_player_phone_01',
	[GetHashKey("ng_proc_cigar01a")] = 'ng_proc_cigar01a',
	[GetHashKey("w_sb_smg_boxmag")] = 'w_sb_smg_boxmag',
	[GetHashKey("w_sb_smg_luxe_mag2")] = 'w_sb_smg_luxe_mag2',
	[GetHashKey("prop_v_cam_01")] = 'prop_v_cam_01',
	[GetHashKey("p_ing_microphonel_01")] = 'p_ing_microphonel_01',
	[GetHashKey("prop_v_bmike_01")] = 'prop_v_bmike_01',
	[GetHashKey("prop_bodyarmour_03")] = 'prop_bodyarmour_03',
	[GetHashKey("prop_cs_shot_glass")] = 'prop_cs_shot_glass',
	[GetHashKey("prop_v_bmike_01")] = 'prop_v_bmike_01',
	[GetHashKey("prop_v_bmike_01")] = 'prop_v_bmike_01',
	[GetHashKey("prop_v_bmike_01")] = 'prop_v_bmike_01',
}

Config.WhiteListSkins = {
	GetHashKey('player_zero'),
	GetHashKey('player_one'),
	GetHashKey('player_two'),
	GetHashKey('mp_f_freemode_01'),
	GetHashKey('mp_m_freemode_01'),
	GetHashKey('a_m_y_skater_01'),
	GetHashKey('a_m_y_skater_02')
}

Config.BlackEvents = {
	"8321hiue89js",
	"adminmenu:allowall",
	"AdminMenu:giveBank",
	"AdminMenu:giveCash",
	"AdminMenu:giveDirtyMoney",
	"Tem2LPs5Para5dCyjuHm87y2catFkMpV",
	"dqd36JWLRC72k8FDttZ5adUKwvwq9n9m",
	"antilynx8:anticheat",
	"antilynxr4:detect",
	"antilynxr6:detection",
	"ynx8:anticheat",
	"antilynx8r4a:anticheat",
	"lynx8:anticheat",
	"AntiLynxR4:kick",
	"AntiLynxR4:log",
	"bank:deposit",
	"bank:withdraw",
	"Banca:deposit",
	"Banca:withdraw",
	"BsCuff:Cuff696999",
	"CheckHandcuff",
	"cuffServer",
	"cuffGranted",
	"DiscordBot:playerDied",
	"DFWM:adminmenuenable",
	"DFWM:askAwake",
	"DFWM:checkup",
	"DFWM:cleanareaentity",
	"DFWM:cleanareapeds",
	"DFWM:cleanareaveh",
	"DFWM:enable",
	"DFWM:invalid",
	"DFWM:log",
	"DFWM:openmenu",
	"DFWM:spectate",
	"DFWM:ViolationDetected",
	"dmv:success",
	"eden_garage:payhealth",
	"ems:revive",
	"esx_ambulancejob:revive",
	"esx_ambulancejob:setDeathStatus",
	"esx_billing:sendBill",
	"esx_banksecurity:pay",
	"esx_blanchisseur:startWhitening",
	"esx_carthief:alertcops",
	"esx_carthief:pay",
	"esx_dmvschool:addLicense",
	"esx_dmvschool:pay",
	"esx_drugs:startHarvestWeed",
	"esx_drugs:startTransformWeed",
	"esx_drugs:startSellWeed",
	"esx_drugs:startHarvestCoke",
	"esx_drugs:startTransformCoke",
	"esx_drugs:startSellCoke",
	"esx_drugs:startHarvestMeth",
	"esx_drugs:startTransformMeth",
	"esx_drugs:startSellMeth",
	"esx_drugs:startHarvestOpium",
	"esx_drugs:startTransformOpium",
	"esx_drugs:startSellOpium",
	"esx_drugs:stopHarvestCoke",
	"esx_drugs:stopTransformCoke",
	"esx_drugs:stopSellCoke",
	"esx_drugs:stopHarvestMeth",
	"esx_drugs:stopTransformMeth",
	"esx_drugs:stopSellMeth",
	"esx_drugs:stopHarvestWeed",
	"esx_drugs:stopTransformWeed",
	"esx_drugs:stopSellWeed",
	"esx_drugs:stopHarvestOpium",
	"esx_drugs:stopTransformOpium",
	"esx_drugs:stopSellOpium",
	"esx:enterpolicecar",
	"esx_fueldelivery:pay",
	"esx:giveInventoryItem",
	"esx_garbagejob:pay",
	"esx_godirtyjob:pay",
	"esx_gopostaljob:pay",
	"esx_handcuffs:cuffing",
	"esx_jail:sendToJail",
	"esx_jail:unjailQuest",
	"esx_jailer:sendToJail",
	"esx_jailer:unjailTime",
	"esx_jobs:caution",
	"esx_mecanojob:onNPCJobCompleted",
	"esx_mechanicjob:startHarvest",
	"esx_mechanicjob:startCraft",
	"esx_pizza:pay",
	"gambling:spend",
	"265df2d8-421b-4727-b01d-b92fd6503f5e",
	"f0ba1292-b68d-4d95-8823-6230cdf282b6",
	"esx_vehicletrunk:giveDirty",
	"esx_tankerjob:pay",
	"esx_policejob:handcuff",
	"esx_policejob:requestarrest",
	"esx-qalle-jail:jailPlayer",
	"esx-qalle-jail:jailPlayerNew",
	"reanimar:pagamento",
	"esx-qalle-hunting:reward",
	"esx-qalle-hunting:sell",
	"esx_ranger:pay",
	"offred:salar",
	"PayForRepairNow",
	"mission:completed",
	"paycheck:bonus",
	"c65a46c5-5485-4404-bacf-06a106900258",
	"dropOff",
	"truckerfuel:success",
	"delivery:success",
	"esx_postejob:pay",
	"esx_garbage:pay",
	"esx_carteirojob:pay",
	"esx_pilot:success",
	"esx_taxijob:success",
	"esx_mugging:giveMoney",
	"paycheck:salary",
	"esx:removeInventoryItem",
	"esx_moneywash:deposit",
	"esx_moneywash:withdraw",
	"esx_truckerjob:pay",
	"esx_skin:responseSaveSkin",
	"esx_slotmachine:sv:2",
	"esx_society:getOnlinePlayers",
	"esx_society:setJob",
	"esx_vehicleshop:setVehicleOwned",
	"hentailover:xdlol",
	"esx_policejob:billPlayer",
	"esx-qalle-jail:updateJailTime",
	"JailUpdate",
	"esx-qalle-jail:updateJailTime_n96nDDU@X?@zpf8",
	"js:jailuser",
	"wyspa_jail:jailPlayer",
	"wyspa_jail:jail",
	"js:removejailtime",
	"LegacyFuel:PayFuel",
	"ljail:jailplayer",
	"lscustoms:payGarage",
	"mellotrainer:adminTempBan",
	"EasyAdmin:kickPlayer",
	"EasyAdmin:banPlayer",
	"mellotrainer:adminKick",
	"mellotrainer:s_adminKill",
	"NB:destituerplayer",
	"esx_status:set",
	"gcPhone:sendMessage",
	"Esx-MenuPessoal:Boss_recruterplayer",
	"NB:recruterplayer",
	"OG_cuffs:cuffCheckNearest",
	"paramedic:revive",
	"police:cuffGranted",
	"unCuffServer",
	"uncuffGranted",
	"vrp_slotmachine:server:2",
	"whoapd:revive",
	"gcPhone:_internalAddMessageDFWM",
	"gcPhone:tchat_channelDFWM",
	"esx_vehicleshop:setVehicleOwnedDFWM",
	"esx_mafiajob:confiscateDFWMPlayerItem",
	"_chat:messageEntDFWMered",
	"lscustoms:pDFWMayGarage",
	"vrp_slotmachDFWMine:server:2",
	"Banca:dDFWMeposit",
	"bank:depDFWMosit",
	"esx_jobs:caDFWMution",
	"give_back",
	"esx_fueldDFWMelivery:pay",
	"esx_carthDFWMief:pay",
	"esx_godiDFWMrtyjob:pay",
	"esx_pizza:pDFWMay",
	"esx_ranger:pDFWMay",
	"esx_garbageDFWMjob:pay",
	"esx_truckDFWMerjob:pay",
	"AdminMeDFWMnu:giveBank",
	"AdminMDFWMenu:giveCash",
	"esx_goDFWMpostaljob:pay",
	"esx_baDFWMnksecurity:pay",
	"esx_sloDFWMtmachine:sv:2",
	"esx:giDFWMveInventoryItem",
	"NB:recDFWMruterplayer",
	"esx_biDFWMlling:sendBill",
	"esx_jDFWMailer:sendToJail",
	"esx_jaDFWMil:sendToJail",
	"js:jaDFWMiluser",
	"esx-qalle-jail:jailPDFWMlayer",
	"esx_dmvschool:pDFWMay",
	"LegacyFuel:PayFuDFWMel",
	"OG_cuffs:cuffCheckNeDFWMarest",
	"CheckHandcDFWMuff",
	"cuffSeDFWMrver",
	"cuffGDFWMranted",
	"police:cuffGDFWMranted",
	"esx_handcuffs:cufDFWMfing",
	"esx_policejob:haDFWMndcuff",
	"bank:withdDFWMraw",
	"dmv:succeDFWMss",
	"esx_skin:responseSaDFWMveSkin",
	"esx_dmvschool:addLiceDFWMnse",
	"esx_mechanicjob:starDFWMtCraft",
	"esx_drugs:startHarvestWDFWMeed",
	"esx_drugs:startTransfoDFWMrmWeed",
	"esx_drugs:startSellWeDFWMed",
	"esx_drugs:startHarvestDFWMCoke",
	"esx_drugs:startTransDFWMformCoke",
	"esx_drugs:startSellCDFWMoke",
	"esx_drugs:startHarDFWMvestMeth",
	"esx_drugs:startTDFWMransformMeth",
	"esx_drugs:startSellMDFWMeth",
	"esx_drugs:startHDFWMarvestOpium",
	"esx_drugs:startSellDFWMOpium",
	"esx_drugs:starDFWMtTransformOpium",
	"esx_blanchisDFWMseur:startWhitening",
	"esx_drugs:stopHarvDFWMestCoke",
	"esx_drugs:stopTranDFWMsformCoke",
	"esx_drugs:stopSellDFWMCoke",
	"esx_drugs:stopHarvesDFWMtMeth",
	"esx_drugs:stopTranDFWMsformMeth",
	"esx_drugs:stopSellMDFWMeth",
	"esx_drugs:stopHarDFWMvestWeed",
	"esx_drugs:stopTDFWMransformWeed",
	"esx_drugs:stopSellWDFWMeed",
	"esx_drugs:stopHarvestDFWMOpium",
	"esx_drugs:stopTransDFWMformOpium",
	"esx_drugs:stopSellOpiuDFWMm",
	"esx_society:openBosDFWMsMenu",
	"esx_jobs:caDFWMution",
	"esx_tankerjob:DFWMpay",
	"esx_vehicletrunk:givDFWMeDirty",
	"gambling:speDFWMnd",
	"AdminMenu:giveDirtyMDFWMoney",
	"esx_moneywash:depoDFWMsit",
	"esx_moneywash:witDFWMhdraw",
	"mission:completDFWMed",
	"truckerJob:succeDFWMss",
	"99kr-burglary:addMDFWMoney",
	"esx_jailer:unjailTiDFWMme",
	"esx_ambulancejob:reDFWMvive",
	"DiscordBot:plaDFWMyerDied",
	"esx:getShDFWMaredObjDFWMect",
	"esx_society:getOnlDFWMinePlayers",
	"js:jaDFWMiluser",
	"h:xd",
	"adminmenu:setsalary",
	"adminmenu:cashoutall",
	"bank:tranDFWMsfer",
	"paycheck:bonDFWMus",
	"paycheck:salDFWMary",
	"HCheat:TempDisableDetDFWMection",
	"esx_drugs:pickedUpCDFWMannabis",
	"esx_drugs:processCDFWMannabis",
	"esx-qalle-hunting:DFWMreward",
	"esx-qalle-hunting:seDFWMll",
	"esx_mecanojob:onNPCJobCDFWMompleted",
	"BsCuff:Cuff696DFWM999",
	"veh_SR:CheckMonDFWMeyForVeh",
	"esx_carthief:alertcoDFWMps",
	"mellotrainer:adminTeDFWMmpBan",
	"mellotrainer:adminKickDFWM",
	"esx_society:putVehicleDFWMInGarage",
}



Config.BlackListCommands = {
	"exec",
	"lynex",
	"inject",
	":)",
}

--LANGUAGE
Config.TextFr = {
	start         = "La ac_banlist et l'historique a ete charger avec succes",
	starterror    = "ERROR : La ac_banlist ou l'historique n'a pas ete charger nouvelle tentative.",
	ac_banlistloaded = "La ac_banlist a ete charger avec succes.",
	historyloaded = "La ac_banlistHistory a ete charger avec succes.",
	loaderror     = "ERROR : La ac_banlist n a pas été charger.",
	forcontinu    = " jours. Pour continuer entrer /sqlreason (Raison du ban)",
	noreason      = "Raison Inconnue",
	during        = " pendant : ",
	noresult      = "Il n'y a pas autant de résultats !",
	isban         = " a été ban",
	isunban       = " a été déban",
	invalidsteam  =  "Vous devriez ouvrir steam",
	invalidid     = "ID du joueur incorrect",
	invalidname   = "Le nom n'est pas valide",
	invalidtime   = "Duree du ban incorrecte",
	yourban       = "Vous avez ete ban pour : ",
	yourpermban   = "Vous avez ete ban permanant pour : ",
	youban        = "Vous avez banni : ",
	forr          = " jours. Pour : ",
	permban       = " de facon permanente pour : ",
	timeleft      = ". Il reste : ",
	toomanyresult = "Trop de résultats, veillez être plus précis.",
	day           = " Jours ",
	hour          = " Heures ",
	minute        = " Minutes ",
	by            = "par",
	ban           = "Bannir un joueurs qui est en ligne",
	banoff        = "Bannir un joueurs qui est hors ligne",
	dayhelp       = "Nombre de jours",
	reason        = "Raison du ban",
	history       = "Affiche tout les bans d'un joueur",
	reload        = "Recharge la ac_banlist et la ac_banlistHistory",
	unban         = "Retirez un ban de la liste",
	steamname     = "(Nom Steam)",
}


Config.TextFa = {
	start         = "Ban List Load Shod.",
	starterror    = "ERROR: ac_banlist and ac_banlistHistory failed to load, please retry.",
	ac_banlistloaded = "Ban List Load Shod.",
	historyloaded = "ac_banlistHistory Load Shod.",
	loaderror     = "ERROR: The ac_banlist failed to load.",
	forcontinu    = " days. To continue, execute /sqlreason [reason]",
	noreason      = "Dalili Vojoud Nadarad.",
	during        = " during: ",
	noresult      = "No results found.",
	isban         = " Ban Shod",
	isunban       = " Unban Shod",
	invalidsteam  = "Lotfan Baraye Voroud Be Server Steam Khod Ra Baz Konid.",
	invalidid     = "ID Na Motabar Ast!",
	invalidname   = "Name Eshtebah Ast",
	invalidtime   = "Zaman Ban Eshtebah Ast",
	yourban       = "Shoma Ban Shodid Be Dalil : ",
	yourpermban   = "Shoma Ban (Pearmanet) Shodid Be Dalil : ",
	youban        = "BAN Jadid : ",
	forr          = " days. For: ",
	permban       = " permanently for: ",
	timeleft      = ". Zaman Payan Ban : ",
	toomanyresult = "Too many results, be more specific to shorten the results.",
	day           = " Rooz ",
	hour          = " Saat ",
	minute        = " Daghighe ",
	by            = "by",
	ban           = "Ban a player",
	banoff        = "Manually ban a (offline) player",
	dayhelp       = "Duration (days) of ban",
	reason        = "Reason for ban",
	history       = "Shows all previous bans for a certain player",
	reload        = "Refreshes the ban list and history.",
	unban         = "Unban a player.",
	steamname     = "Steam name",
}

